### PR TITLE
Add a wide modifier to Modal component

### PR DESCRIPTION
**Pull request by koddsson**
I want to make a modal wide.

### CODE REVIEW

**Comment by thellimist** [comment]
I couldn't find the css class `cf-modal--wide`.

**Comment by koddsson** [comment]
I could be wrong but I think the use provides there own styles and so it's just a way for users to be able attach a classname to a component without allowing them to pass the classname directly down.

**Comment by jwineman** [comment]
Can you update the docs and example too?

**Comment by koddsson** [comment]
Sure! I'm guessing [this](https://github.com/cloudflare/cf-ui/blob/master/packages/cf-component-modal/example/basic/component.js) is the example but I'm having a hard time finding the docs. Is it maybe just updating the `README.md`?

**Comment by jwineman** [comment]
Yup, github pages are automatically generated off the example/ folder and README.md.  As long as those are updated to reflect the changes you're making we should be good. 

Can test with:
```
$ npm run examples:build:external # Build the example site with CloudFlare's external styles
$ open dist/index.html
```

**Comment by koddsson** [comment]
So I wasn't sure on what to put in the README. Should I put in something similar as what I did in the examples or just not bother since it's a optional prop?

**Comment by koddsson** [comment]
So what happens now? How can I get this published and out so I can start using it?

**Comment by jwineman** [comment]
You can merge and instructions for releasing are here:

https://github.com/cloudflare/cf-ui/blob/master/CONTRIBUTING.md#publishing-packages

**Comment by koddsson** [comment]
I don't have write access to this repo 😅

**Comment by jwineman** [comment]
@terinjokes any update on getting CF UI under the Cloudflare npm org?

**Pull request merged**
