### PR TITLE
use pagination background color from the new design colors

### PR DESCRIPTION
**Pull request by sejoker**
screen shot 2017-05-22 at 9 09 56 pm

### CODE REVIEW

**Comment by manatarms** [comment]
@sejoker Snapshots need update

**Comment by koddsson** [comment]
Actually maybe my use case should just be a different theme?

**Comment by sejoker** [comment]
@koddsson make sense to me. In my case I need only `dotted` style. Not aware of our usages of `cf-component-pagination` in the dashboard

**Comment by koddsson** [comment]
>Not aware of our usages of cf-component-pagination in the dashboard

Yup. We're adding the first one right now and it looks understandably out of place. Jut added #204 to add the theme and working on that now.

**Pull request merged**
