### PR TITLE
Add onCopy prop to CopyableTextArea

### PR DESCRIPTION
**Pull request by Aweary**
Congrats on the OSS release! 🔥 

It would be nice if `CopyableTextArea` let you respond to a successful copy event. This makes that happen.

I tried adding a test, but there aren't any tests for `CopyableTextArea` at all and karma was giving me some trouble, so I'll have to figure that out.

### CODE REVIEW

**Comment by Aweary** [comment]
Closing since it doesn't look like you guys are really maintaining this 😢

**Comment by jwineman** [comment]
Hi @Aweary,

We are maintaining this.  There has been some confusion internally on who owns it.  I can't look at this PR right now but I'll add it to my TODO list.  I'll respond by the end of the week.

Thanks,
John

**Comment by Aweary** [comment]
@jwineman thanks for the quick response! 👍

**Comment by jwineman** [comment]
Thanks for the PR!  Sorry it took so long to get back to you.

**Pull request merged**
