### PR TITLE
chore(cf-component-card): Fixed top percentage for arrow

### PR DESCRIPTION
**Pull request by manatarms**
So some style is off in cf-styleguide. Trying to hunt it down. But the correct percentage for aligning the arrow in next is 51%.

screen shot 2017-08-24 at 3 17 23 pm

### CODE REVIEW

**Comment by hturan** [comment]
Almost certain this will be to do with `line-height`.

**Comment by manatarms** [comment]
Thanks @hturan

**Comment by manatarms** [comment]
This should fix the card drawers! Thanks @hturan  🥇

**Comment by hturan** [comment]
@manatarms No worries!

**Comment by manatarms** [comment]
I'm going to merge this so I can publish and continue with the migration. Feel free to reopen.

**Pull request merged**
