### PR TITLE
chore(cf-component-box): Added missing display table props

### PR DESCRIPTION
**Pull request by manatarms**

### CODE REVIEW

**Comment by koddsson** [comment]
** Not a comment on this PR but rather cf-ui as a whole **

It's kind of ridiculous that we need to do stuff like this IMHO.

**Comment by manatarms** [comment]
@koddsson I totally agree. But I feel this is a side effect of our Fela migration. Once we figure all the props we need, it should stabilize :)

**Comment by koddsson** [comment]
I'm not sure @manatarms, but I guess time will tell :)

**Comment by tajo** [comment]
> It's kind of ridiculous that we need to do stuff like this IMHO.

You don't *really* need to do that. You can use `createComponent`. `<Box />` was never meant as a full-featured replacement. It's more an experiment and I think it's fine for extra margin/padding but we definitely don't have to copy&paste the whole CSS spec into it.

**Comment by koddsson** [comment]
Does it just work like this?

```js
createComponent({ backgroundColor: 'red' }, Box)
```

**Pull request merged**
