### PR TITLE
chore(cf-style-const): Rearrange colors

### PR DESCRIPTION
**Pull request by manatarms**
screen shot 2017-08-29 at 5 47 16 pm

### CODE REVIEW

**Comment by manatarms** [comment]
@neynah Does this look good?

**Comment by manatarms** [comment]
NP anytime.

**Comment by tajo** [comment]
http://www.alanzucconi.com/2015/09/30/colour-sorting/ fun stuff :)

**Comment by manatarms** [comment]
@neynah what do you think 
automate_1allthethings

**Pull request merged**
