### PR TITLE
Added 'vertical' prop to ButtonGroup

### PR DESCRIPTION
**Pull request by hturan**
This PR adds a `vertical` prop to `ButtonGroup`, allowing for vertical groups of buttons, as seen in the below screenshot:

screen shot 2017-08-07 at 11 42 11

### CODE REVIEW

**Comment by koddsson** [comment]
Wait with merging this until I figure the deployment out? It shouldn't be more than an hour 🙏

**Comment by hturan** [comment]
> Wait with merging this until I figure the deployment out? It shouldn't be more than an hour 🙏

Sure thing!

**Comment by koddsson** [comment]
I rolled back the automatic deployment changes. Feel free to publish manually when ever you'd lik.e

**Comment by hturan** [comment]
> I like the feature! One thing is we could do better IMO if instead adding ad hoc vertical property we follow flex with direction value of column and row.

Good idea! All done 👍

**Pull request merged**
