### PR TITLE
Adds an 'extra-wide' option to modal.

### PR DESCRIPTION
**Pull request by jculvey**
Wide just wasn't cutting it.

### CODE REVIEW

**Comment by wyuenho** [comment]
How wide is extra-wide?

**Comment by hturan** [comment]
If we're going this route can we do:

```js
if (this.props.width) {
  modalClassName += ` cf-modal--${this.props.width}`;
}
```

...to avoid when we need `super-wide` in the future?

**Comment by jwineman** [comment]
Is this a pain to style at the page level?

**Comment by jculvey** [comment]
@wyuenho it's 800px.

**Comment by wyuenho** [comment]
Can you update the examples, readme and tests?

**Comment by jculvey** [comment]
@jwineman yeah, unfortunately its plain impossible at the page level. Since the cf-ui Modal uses `react-gateway`, it gets re-parented to another DOM node at the bottom of the page, which makes it impossible to wrap it in something with a class we can target :/

**Comment by jculvey** [comment]
I added a test, updated the example, and changed the functionality the way @hturan described.

I couldn't get the examples to work for me locally. It complains about missing semicolons in both cf-component-flex and cf-component-progress.

```bash
[13:19:38] Starting 'examplesDevVendor'...
[13:19:39] 'examplesBuildHtml' errored after 548 ms
[13:19:39] SyntaxError: Unexpected token, expected ; (1:6)
    at Parser.pp$5.raise (/Users/jculveyhouse/cf-repos/cf-ui/node_modules/babylon/lib/index.js:4246:13)
```

**Comment by jwineman** [comment]
```
$ git pull origin master
$ npm run build
$ npm run bootstrap
$ npm run examples:build:internal
```
Works for me

**Comment by jculvey** [comment]
K I ran the examples and they look fine. Anything else needed for this?

**Comment by hturan** [comment]
> K I ran the examples and they look fine. Anything else needed for this?

Nope, let's get this in. I'm tired of my thin modals.

**Pull request merged**
