### PR TITLE
[WIP] Fix tests in CI and also just fix 'em

### PR DESCRIPTION
**Pull request by koddsson**

### CODE REVIEW

**Comment by koddsson** [comment]
The failures locally don't show up on CI at all (albeit there's a bunch of `console.error`s). Gonna dig better into the local failures. Only difference so far seems to be mac os x vs. linux.

Are you getting a clean run after pulling master @sejoker ?

**Comment by koddsson** [comment]
Only got one failure after these changes

```
Summary of all failing tests
 FAIL  packages/cf-component-notifications/test/Notification.js
  ● should pause the timeout while the mouse is hovering the notification

    TypeError: Cannot read property '_currentElement' of null

      at getListener (node_modules/react-dom/lib/EventPluginHub.js:156:55)
      at accumulateDispatches (node_modules/react-dom/lib/EventPropagators.js:80:20)
      at accumulateDirectDispatchesSingle (node_modules/react-dom/lib/EventPropagators.js:95:5)
      at forEachAccumulated (node_modules/react-dom/lib/forEachAccumulated.js:26:8)
      at Object.accumulateDirectDispatches (node_modules/react-dom/lib/EventPropagators.js:112:3)
      at Object.mouseEnter (node_modules/react-dom/lib/ReactTestUtils.js:345:24)
      at Object.<anonymous> (packages/cf-component-notifications/test/Notification.js:71:32)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)


Test Suites: 1 failed, 98 passed, 99 total
Tests:       1 failed, 248 passed, 249 total
Snapshots:   172 passed, 172 total
Time:        20.99s, estimated 29s
Ran all test suites.
```

**Comment by koddsson** [comment]
Could you try this branch out @hturan ?

**Comment by hturan** [comment]
I get all tests passing when I run this branch on node 7 and also do `yarn add inline-style-prefixer cssbeautify` 👌

**Comment by manatarms** [comment]
I'm a little confused. Why are these not failing on CI?

**Comment by koddsson** [comment]
I have no idea :(

**Comment by koddsson** [comment]
Actually let me make a commit that breaks a test just to make sure that CI catches that.

**Comment by manatarms** [comment]
What!!!! The tests passed.

**Comment by koddsson** [comment]
I have no idea what's going on

**Comment by koddsson** [comment]
I'm gonna close this PR for now. If someone wants to pick this up feel free to comment or re-open but I'm unsure on how to proceed.

**Comment by sejoker** [comment]
There are 2 issues here:

- make CI fail/pass when tests pass/fail
- add missing dependencies into cf-style-provider (css-beatify, inline-style-prefixer) because Fela author reluctant to follow semver.

cc @tajo

**Pull request closed without merging**
