### PR TITLE
fix(cf-component-card): minor integration issues

### PR DESCRIPTION
**Pull request by koddsson**
Fixing some minor integration issues into the dashboard after merging:
f5b9eefe847d28a700b6e41b68824c1a9f33e9c3.

### CODE REVIEW

**Comment by manatarms** [comment]
@koddsson is this something that got fixed?

**Comment by koddsson** [comment]
Nope. If memory serves me right, this is something about abstracting the `Control` subcomponent out so it can be overwritten in certain situations.

**Comment by manatarms** [comment]
Are there places using the control? Or is this some future requirement thing?

**Comment by manatarms** [comment]
@koddsson I think I figured it :D 
Thanks for the super quick response <3

**Comment by koddsson** [comment]
No worries 😄

**Comment by manatarms** [comment]
Closing this. I think I fixed it.

**Pull request closed without merging**
