### PR TITLE
Don't merge: recover of npm owner scripts

### PR DESCRIPTION
**Pull request by sejoker**
This reverts commit fac240c468ea189965ce13c7f007066fcfd4e6bc.

Due to issues with publishing to Cloudflare npm organization we may consider using old approach for the time being.

### CODE REVIEW

**Comment by jwineman** [comment]
Are the issues they don't have access? Give me a list of who needs access and I'll get it done today.

**Comment by wyuenho** [comment]
It would help us a lot if you could make sure everyone is a maintainer on every cf-ui package on npm.

**Comment by jwineman** [comment]
I'll bug @toekneestuck about this

**Comment by wyuenho** [comment]
@jwineman @tajo @toekneestuck No need for this any more correct? Just add an npm user to and org account and done from now on?

**Comment by tajo** [comment]
Let's wait with this. I don't think so we will be releasing any new packages in next few weeks and npm can fix it in meantime.

**Comment by jwineman** [comment]
@wyuenho correct, I think.  The one caveat is whoever releases any new packages needs to make sure they add them to the org and not the personal account.

**Comment by tajo** [comment]
I have admin rights to our npm org now, so if you need to publish a completely new cf-ui package, let me do it. Otherwise, we are fine.

**Pull request closed without merging**
